FORTH-WORDLIST TASK-WORDLIST 2 SET-ORDER

REQUIRE src/forth/bchan.fs

20 NEW-BCHAN CONSTANT MY-BCHAN

VARIABLE TERMINATE FALSE TERMINATE !

: SENDER
  0. 0 BEGIN
    TERMINATE @ 0=
  WHILE
    DUP MY-BCHAN SEND-BCHAN 1+
    DUP $1000 MOD 0= IF
      YIELDS ROT 2 PICK 2 PICK 6 ROLL 6 ROLL D- D>F
      1024E FSWAP F/ ." <" (F.) ." > "
    THEN
    \ DUP $1000 MOD 0= IF DUP ." <" 16 (BASE.) ." > " THEN
  REPEAT ;

: RECEIVER
  0. BEGIN TERMINATE @ 0= WHILE
    MY-BCHAN TRY-RECV-BCHAN 0= IF
      DROP YIELD
    ELSE
      $1000 MOD 0= IF
        YIELDS 2DUP 5 ROLL 5 ROLL D- D>F
        1024E FSWAP F/ ." [" (F.) ." ] "
      THEN
      \ DUP $1000 MOD 0= IF ." [" 16 (BASE.) ." ] " ELSE DROP THEN
    THEN
  REPEAT ;

: DO-RUN

  0 ['] RECEIVER SPAWN-SIMPLE-FREE-DATA-ON-EXIT DROP
  0 ['] SENDER SPAWN-SIMPLE-FREE-DATA-ON-EXIT DROP

  KEY DROP TRUE TERMINATE ! ;

DO-RUN
