FORTH-WORDLIST TASK-WORDLIST 2 SET-ORDER

REQUIRE src/forth/bchan.fs

20 NEW-BCHAN CONSTANT MY-BCHAN

VARIABLE TERMINATE FALSE TERMINATE !

: SENDER
  0 BEGIN
    TERMINATE @ 0=
  WHILE
    DUP MY-BCHAN TRY-SEND-BCHAN 0= IF
      ." x" YIELD
    ELSE
      ." ."
    THEN
    1+ 
  REPEAT ;

: RECEIVER
  BEGIN
    TERMINATE @ 0=
  WHILE
    MY-BCHAN TRY-RECV-BCHAN 0= IF
      DROP YIELD
    ELSE
      16 BASE.
    THEN
  REPEAT ;

0 ' RECEIVER SPAWN-SIMPLE-FREE-DATA-ON-EXIT DROP
0 ' SENDER SPAWN-SIMPLE-FREE-DATA-ON-EXIT DROP

: DO-TERMINATE KEY DROP TRUE TERMINATE ! ;

DO-TERMINATE
