\ Copyright (c) 2018, Travis Bemann
\ All rights reserved.
\ 
\ Redistribution and use in source and binary forms, with or without
\ modification, are permitted provided that the following conditions are met:
\ 
\ 1. Redistributions of source code must retain the above copyright notice,
\    this list of conditions and the following disclaimer.
\ 
\ 2. Redistributions in binary form must reproduce the above copyright notice,
\    this list of conditions and the following disclaimer in the documentation
\    and/or other materials provided with the distribution.
\ 
\ 3. Neither the name of the copyright holder nor the names of its
\    contributors may be used to endorse or promote products derived from
\    this software without specific prior written permission.
\ 
\ THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
\ AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
\ IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
\ ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
\ LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
\ CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
\ SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
\ INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
\ CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
\ ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
\ POSSIBILITY OF SUCH DAMAGE.

REQUIRE buffer.fs

4 NEW-BUFFER CONSTANT MY-BUFFER

: BUFFER. ( buffer -- ) CR DUP GET-BUFFER-LENGTH . GET-BUFFER TYPE ;

: BUFFER-TEST ( -- )
  MY-BUFFER BUFFER.
  S" foobaz" MY-BUFFER APPEND-BUFFER
  MY-BUFFER BUFFER.
  S" qux" 6 MY-BUFFER WRITE-BUFFER
  MY-BUFFER BUFFER.
  S" bar" 3 MY-BUFFER INSERT-BUFFER
  MY-BUFFER BUFFER.
  S" *" MY-BUFFER PREPEND-BUFFER
  MY-BUFFER BUFFER.
  BL 4 MY-BUFFER INSERT-BYTE-BUFFER
  MY-BUFFER BUFFER.
  BL 8 MY-BUFFER INSERT-BYTE-BUFFER
  MY-BUFFER BUFFER.
  BL 12 MY-BUFFER INSERT-BYTE-BUFFER
  MY-BUFFER BUFFER.
  [CHAR] * MY-BUFFER APPEND-BYTE-BUFFER
  MY-BUFFER BUFFER.
  1 12 MY-BUFFER REMOVE-BUFFER
  MY-BUFFER BUFFER.
  1 8 MY-BUFFER REMOVE-BUFFER
  MY-BUFFER BUFFER.
  1 4 MY-BUFFER REMOVE-BUFFER
  MY-BUFFER BUFFER.
  1 MY-BUFFER REMOVE-START-BUFFER
  MY-BUFFER BUFFER.
  1 MY-BUFFER REMOVE-END-BUFFER
  MY-BUFFER BUFFER.
  6 3 MY-BUFFER REMOVE-BUFFER
  MY-BUFFER BUFFER.
  [CHAR] b 3 MY-BUFFER WRITE-BYTE-BUFFER
  MY-BUFFER BUFFER.
  [CHAR] a 4 MY-BUFFER WRITE-BYTE-BUFFER
  MY-BUFFER BUFFER.
  [CHAR] r 5 MY-BUFFER WRITE-BYTE-BUFFER
  MY-BUFFER BUFFER.
  [CHAR] + MY-BUFFER PREPEND-BYTE-BUFFER
  MY-BUFFER BUFFER.
  [CHAR] + 7 MY-BUFFER INSERT-BYTE-BUFFER
  MY-BUFFER BUFFER. ;

BUFFER-TEST