GET-ORDER GET-CURRENT BASE @

DECIMAL
FORTH-WORDLIST TASK-WORDLIST 2 SET-ORDER
FORTH-WORDLIST SET-CURRENT

NEW-LOCK CONSTANT PROFILE-LOCK
VARIABLE LAST-PROFILE-WORD 0 LAST-PROFILE-WORD !
VARIABLE PROFILE-INSTRUMENT-ENABLE FALSE PROFILE-INSTRUMENT-ENABLE !
VARIABLE PROFILE-ENABLE FALSE PROFILE-ENABLE !

: UPDATE-LAST-PROFILE-WORD ( addr -- addr )
  PROFILE-LOCK LOCK LAST-PROFILE-WORD @ SWAP LAST-PROFILE-WORD !
  PROFILE-LOCK UNLOCK ;

BEGIN-STRUCTURE PROFILE-DATA-SIZE
  FIELD: PROFILE-XT
  FIELD: PROFILE-NEXT
  FIELD: PROFILE-COUNT
END-STRUCTURE

: SET-PROFILE-INSTRUMENT-ENABLE ( f -- ) PROFILE-INSTRUMENT-ENABLE ! ;

: GET-PROFILE-INSTRUMENT-ENABLE ( -- f ) PROFILE-INSTRUMENT-ENABLE @ ;

: SET-PROFILE-ENABLE ( f -- ) PROFILE-ENABLE ! ;

: GET-PROFILE-ENABLE ( -- f ) PROFILE-ENABLE @ ;

: PROFILE. ( -- )
  LAST-PROFILE-WORD @
  BEGIN DUP 0<> WHILE
    CR DUP PROFILE-XT @ DUP NAME>STRING TYPE SPACE 16 BASE.
    DUP PROFILE-COUNT @ 10 BASE.
    PROFILE-NEXT @
  REPEAT
  DROP ;

: RESET-PROFILE ( -- )
  LAST-PROFILE-WORD @
  BEGIN DUP 0<> WHILE
    DUP 0 SWAP PROFILE-COUNT !
    PROFILE-NEXT @
  REPEAT
  DROP ;

: COMPILE-PROFILE ( -- )
  GET-PROFILE-INSTRUMENT-ENABLE IF
    & BRANCH HERE [ PROFILE-DATA-SIZE 2 CELLS + ] LITERAL + ,
    0 , HERE UPDATE-LAST-PROFILE-WORD LATESTXT , , HERE 0 ,
    & GET-PROFILE-ENABLE & IF
      & (LITERAL) 1 , & (LITERAL) , & +!
    & THEN
  THEN ;

: :NONAME ( -- xt ) :NONAME COMPILE-PROFILE ;

: : ( "name" -- ) : COMPILE-PROFILE ;

BASE ! SET-CURRENT SET-ORDER