GET-ORDER GET-CURRENT BASE @

DECIMAL
FORTH-WORDLIST TASK-WORDLIST 2 SET-ORDER
FORTH-WORDLIST SET-CURRENT

NEW-LOCK CONSTANT PROFILE-LOCK
VARIABLE LAST-PROFILE-WORD 0 LAST-PROFILE-WORD !

: UPDATE-LAST-PROFILE-WORD ( addr -- addr )
  PROFILE-LOCK LOCK LAST-PROFILE-WORD @ SWAP LAST-PROFILE-WORD !
  PROFILE-LOCK UNLOCK ;

BEGIN-STRUCTURE PROFILE-DATA-SIZE
  FIELD: PROFILE-XT
  FIELD: PROFILE-NEXT
  FIELD: PROFILE-COUNT
END-STRUCTURE

: PROFILE. ( -- )
  LAST-PROFILE-WORD @
  BEGIN DUP 0<> WHILE
    CR DUP PROFILE-XT @ DUP NAME>STRING TYPE SPACE 16 BASE.
    DUP PROFILE-COUNT @ 10 BASE.
    PROFILE-NEXT @
  REPEAT
  DROP ;

: RESET-PROFILE ( -- )
  LAST-PROFILE-WORD @
  BEGIN DUP 0<> WHILE
    DUP 0 SWAP PROFILE-COUNT !
    PROFILE-NEXT @
  REPEAT
  DROP ;

: COMPILE-PROFILE ( -- )
  & BRANCH HERE [ PROFILE-DATA-SIZE 2 CELLS + ] LITERAL + ,
  0 , HERE UPDATE-LAST-PROFILE-WORD LATESTXT , , HERE 0 ,
  & (LITERAL) 1 , & (LITERAL) , & +! ;

: :NONAME ( -- xt ) :NONAME COMPILE-PROFILE ;

: : ( "name" -- ) : COMPILE-PROFILE ;

BASE ! SET-CURRENT SET-ORDER